linters:
  enable:
    - gocritic
    - goimports
    - revive
    - godox
    - gofmt
    - unparam
    - bodyclose
    - nilerr
    - nilnil
    # - gosec

run:
  timeout: 2m  # Устанавливаем разумный таймаут, чтобы не тратить много времени на анализ.
